### ISSUE TITLE
Comments in TOML files not properly coloured

### ISSUE THREAD

**Issue by neilyoung** [Amomum/Verdigris_theme#1]
Thanks for sharing this great theme. I'm more than happy with it.

Just once: A comment is not properly coloured (e.g. green) in .toml files, so it is a bit hard to see that.

![image](https://user-images.githubusercontent.com/731020/97090983-aa88be00-1638-11eb-840c-98b490237a3b.png)

**Comment by Amomum** [comment]
Oh dear, that was so long ago :)
I think the issue is that .toml files are colored differently and I just didn't include TOML syntax in the theme.

The issue is in VSCode?

**Comment by neilyoung** [comment]
Right :)

**Comment by neilyoung** [comment]
Oh I see, 4 years.... Please ignore :)

**Comment by Amomum** [comment]
Too late, I'm already in :D 
Do you by any chance use 'Better TOML' for TOML syntax highlight?

**Comment by neilyoung** [comment]
No, not to my knowledge

**Comment by Amomum** [comment]
Please try new version locally; I tried to make TOML coloring more closely matching the rest. 
If it doesn't work for some reason feel free to reopen this.

If it works, I'll publish new version to VSCode marketplace.

**Comment by neilyoung** [comment]
Perfect. This fixes the issue. Thank you very much!

![image](https://user-images.githubusercontent.com/731020/97101548-c4f58280-169e-11eb-970f-fec3a5cf8b1b.png)

**Comment by roman-khazanskii** [comment]
Great! I added some more coloring for TOML and published it to marketplace.

**Comment by neilyoung** [comment]
Many thanks again. Good job after 4 years :)

**Comment by Amomum** [comment]
Great! I added some more coloring for TOML and published it to marketplace."

(used wrong account before, sorry)

**Comment by neilyoung** [comment]
...maybe just one more thing in case you would touch that again. I guess you could apply the same styling to `Cargo.lock` as well. It is not a file, which is examined very often, but just for parity :) No urgency, of course.

**Comment by Amomum** [comment]
Hmm, I just checked - and looks like most of the Cargo.lock should already be colored:

![image](https://user-images.githubusercontent.com/4990494/97112163-d026cd80-16f3-11eb-9347-af79faddb4a7.png)

**Comment by neilyoung** [comment]
Oh, it's completely black and white here :)

![image](https://user-images.githubusercontent.com/731020/97112343-0d835f00-16e4-11eb-8ae0-e3627da2365b.png)

**Comment by Amomum** [comment]
Are you using version 0.0.2 from the marketplace?

**Comment by neilyoung** [comment]
Yes:

![image](https://user-images.githubusercontent.com/731020/97112464-b5992800-16e4-11eb-8cfe-68b7ebc7ae85.png)


BTW: I just rated you here https://marketplace.visualstudio.com/items?itemName=amomum.theme-verdigris-light&ssr=false#review-details

**Comment by neilyoung** [comment]
OT: You can really be proud of you: 4 years, zero issues, about 4.300 downloads - top!

**Comment by neilyoung** [comment]
Using it on macOS, if that matters...

**Comment by neilyoung** [comment]
Just removed and installed it again. Same result. But don't bother, I'm fine.

**Comment by Amomum** [comment]
>OT: You can really be proud of you: 4 years, zero issues, about 4.300 downloads - top!

Thanks :) Might accidentally be the most useful thing I did so far :D 

>Just removed and installed it again. Same result. But don't bother, I'm fine.

Hmm, that's strange. Are you using any extensions for TOML or lock-files syntax highlighting?

**Comment by neilyoung** [comment]
> Hmm, that's strange. Are you using any extensions for TOML or lock-files syntax highlighting?

Well, I think you are right. I had a couple, one mentioned `Better TOML`. Disabled it all, now all colours are gone from all Cargo files.

![image](https://user-images.githubusercontent.com/731020/97113805-f2691d00-16ec-11eb-84c6-8126da4dec13.png)

**Comment by Amomum** [comment]
Hmmm, interesting.
I disabled all rust or toml-related extensions I had and still get highlighting in cargo.lock files.

Would you be able to post a screenshot of "Developer: Inspect Editor Tokens and Scopes" sorta like this one?
![image](https://user-images.githubusercontent.com/4990494/97216754-58ca6a00-17d7-11eb-84eb-b770e50ac02b.png)

**Comment by neilyoung** [comment]
Yepp, here you are:

![image](https://user-images.githubusercontent.com/731020/97218392-ebafd800-17c8-11eb-80ca-c431eead8d05.png)

**Comment by Amomum** [comment]
According to https://github.com/microsoft/vscode/commit/f2f8b7cb08d80184d1df76234b236760ae9a72f5, you need to use an extension to get TOML highlighting.

Try installing some (like `TOML Language Support` or `Better TOML`)? I'm not sure how I get highlighting with them disabled though..

**Comment by neilyoung** [comment]
Better TOML is already installed

![image](https://user-images.githubusercontent.com/731020/97219099-d1c2c500-17c9-11eb-89ef-e4091cb2b8d3.png)

Did install "TOML Language support" now and tadaa...

![image](https://user-images.githubusercontent.com/731020/97219177-eb640c80-17c9-11eb-93a0-02c6685e9b18.png)

Maybe with this I would already having had colours in your previous version...

**Comment by Amomum** [comment]
Hooray! :tada:

**Comment by neilyoung** [comment]
Hmm. After having had an issue with Rust analyzer (https://github.com/rust-analyzer/rust-analyzer/issues/6433), which ended up in a new version of RA installed from local, all colours are gone again from _all_ .TOML files :(

**Comment by neilyoung** [comment]
Arghhh... Disregard please. My bad.
